### PR TITLE
Moved cornflakes to local `xrbk` crate

### PR DESCRIPTION
**Pull request by Syudagye**
Moved everything except tests, and added a bit of documentation.
Not sure what else to do here for now.

### CODE REVIEW

**Comment by Antikyth** [comment]
Do the macros still expand correctly (e.g. in `x11/events`)?  If so, this should be merged now, yes?

**Comment by Syudagye** [comment]
The only thing left to do is implementing the `Wrapper` trait, since i copied the files before [this commit](https://github.com/XdotRS/cornflakes/commit/74e26984dba91068c26fdae7a53d9585b3d7e0a3)

**Comment by Syudagye** [comment]
> Do the macros still expand correctly (e.g. in `x11/events`)? If so, this should be merged now, yes?

I think so yes, it's building properly in f1936e1, so other that the  `Wrapper` trait missing from `xrbk`, nothing else seems to be an issue

**Comment by Antikyth** [comment]
> > Do the macros still expand correctly (e.g. in `x11/events`)? If so, this should be merged now, yes?
> 
> I think so yes, it's building properly in f1936e1, so other that the  `Wrapper` trait missing from `xrbk`, nothing else seems to be an issue

Ah, okay :)  Maybe if you could copy the Wrapper trait over then this can be merged?

**Comment by Syudagye** [comment]
I tried a build, and it succeeded, so I think it's ready to be merged !

**Pull request merged**
